import io.vavr.control.Try;
import org.zalando.problem.Problem;

import java.net.URI;

import static javax.ws.rs.core.Response.Status.BAD_REQUEST;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static Try<String> functionWithSuccessValue() {

        return Try.success("success");
    }

    public static Try<String> functionWithError(String prevVal) {

        return Try.failure(Problem.builder()
            .withType(URI.create("https://example.org/out-of-stock"))
            .withTitle("Out of Stock")
            .withStatus(BAD_REQUEST)
            .withDetail("Item B00027Y5QG is no longer available")
            .build());
    }

    public static Try<String> callFunction() {

        return functionWithSuccessValue()
            .flatMap(Library::functionWithError);
    }

    public static String functionWithException(String prevVal) {

        throw new RuntimeException("sampleException");
    }

    public static Try<String> callFunctionWithException() {

        return functionWithSuccessValue()
            .mapTry(Library::functionWithException);
    }

}
